DROP TABLE OUTBOUND.summ
CREATE TABLE OUTBOUND.SUMM(CUSTOMERID NCHAR(5),COMPANYNAME NVARCHAR(40),CUSTOMERNAME NVARCHAR(30),CUSTADDRESS NVARCHAR(60),EMPLOYEEID INT,EMPLOYEENAME NVARCHAR(10),SALESID INT,ITEMDI INT,PRODUCTNAME NVARCHAR(40),SUPPLIERID INT)
SELECT * FROM OUTBOUND.SUMM

ALTER TABLE OUTBOUND.SUMM
ADD CATEGORYNAME NVARCHAR(30)
Select DISTINCT(DC.CUSTOMERID),DC.COMPANYNAME,DC.CONTACTNAME,DC.ADDRESS	,E.EMPLOYEEID,E.EMPLOYEENAME ,S.SALESID,DM.itemid,DM.PRODUCTNAME,DM.SUPPLIERID,CG.CATEGORYID,CG.CATEGORYNAME
from REF.DIM_CUSTOMER DC,REF.DIM_EMPLOYEE E,REF.DIM_PRODUCT DM,REF.DIM_CATEGORY CG


SELECT DISTINCT * FROM REF.LKP_CUST_SALES

SELECT * FROM Employees

ALTER TABLE OUTBOUND.SUMM
ADD EMPLOYEENAME NVARCHAR(10)
SELECT * FROM OUTBOUND.SUMM

DROP TABLE OUTBOUND.SUMM

drop TABLE DIMEMPLOYEE
DROP CONSTRAINT PK_DimEmployee
alter table factsales
drop constraint FK_FactSales_Dimemployee
SELECT * FROM REF.[SALES DETAILS]
ALTER TABLE REF.[SALES DETAILS]
ADD DATES DATE 
;WITH A AS
(
  SELECT GETDATE()-365 AS TDATE
  UNION ALL
  SELECT DATEADD(DAY,1,A.TDATE) 
  FROM A
  WHERE A.TDATE<=GETDATE()+365
  )
 INSERT INTO REF.[SALESDETAILS_N](SALESID,PRODUCTID,UNITPRICE,QUANTITY,DISCOUNT,DATES)
 SELECT [Order Details].[[SALESID]]],[Order Details].ProductID,[Order Details].UnitPrice,[Order Details].QUANTITY,[ORDER DETAILS].Discount,A.TDATE FROM A,[Order Details]
 OPTION(MAXRECURSION 7000);

 ALTER TABLE REF.[SALES DETAILS]
 DROP COLUMN DATES
 
 SELECT  DISTINCT * FROM REF.LKP_CUST_SALES




 CREATE TABLE REF.SALESDETAILS_N(SALESID INT,PRODUCTID INT,UNITPRICE MONEY,QUANTITY SMALLINT,DISCOUNT REAL,DATES DATE)
 SELECT * FROM REF.SALESDETAILS_N

 

