
(Select DISTINCT(DC.CUSTOMERID),DC.COMPANYNAME,DC.CONTACTNAME,DC.ADDRESS	,S.SALESID,DM.itemid,DM.PRODUCTNAME,DM.SUPPLIERID,CG.CATEGORYID,CG.CATEGORYNAME,E.EMPLOYEEID,E.EMPLOYEENAME
from REF.DIM_CUSTOMER DC --,REF.DIM_CATEGORY CG,ref.DIM_PRODUCT DM,REF.DIM_EMPLOYEE E
inner join ref.DIM_PRODUCT dm on CG.CATEGORYID=dm.categoryid

--inner join ref.LKP_CUST_SALES cs on DC.customerid=cs.customerid

INNER JOIN MART.SALES S   ON  E.EMPLOYEEID=S.EMPLOYEEID)

FETCH FIRST 1000 ROWS
 
--INNER JOIN  MART.SALES S ON S.EMPLOYEEID = E.EMPLOYEEID
--INNER JOIN REF.LKP_CUST_SALES CS ON S.SALESID=CS.salesid
--INNER JOIN MART.SALES S ON S.ITEMID=DM.itemid


--INSERT INTO OUTBOUND.SUMM(EMPLOYEEID,EMPLOYEENAME)
--Select DE.EMPLOYEEID,DE.EMPLOYEENAME	
--from REF.DIM_EMPLOYEE DE
--INNER JOIN MART.SALES S   ON DE.EMPLOYEEID=S.EMPLOYEEID

INSERT INTO OUTBOUND.SUMM
SELECT 
	A.SALESID,A.EMPLOYEEID,A.ITEMID,
	C.CUSTOMERID,C.CONTACTNAME,C.ADDRESS,C.COMPANYNAME,
	D.PRODUCTNAME,D.SUPPLIERID,D.categoryid,
	E.EMPLOYEENAME,
	F.CATEGORYNAME

FROM MART.SALES A
INNER JOIN REF.LKP_CUST_SALES B ON A.SALESID = B.salesid
INNER JOIN REF.DIM_CUSTOMER C ON B.customerid = C.CUSTOMERID
INNER JOIN REF.DIM_PRODUCT D ON A.itemid=D.itemid
INNER JOIN REF.DIM_EMPLOYEE E ON A.EMPLOYEEID=E.EMPLOYEEID
INNER JOIN REF.DIM_CATEGORY F ON D.categoryid=F.CATEGORYID

CREATE TABLE OUTBOUND.SUMM(SALESID INT,EMPLOYEEID INT,ITEMID INT,CUSTOMERID NCHAR(5),CONTACTNAME NVARCHAR(30),ADDRESS NVARCHAR(60),COMPANYNAME NVARCHAR(40), PRODUCTNAME NVARCHAR(40),SUPPLIERID INT,CATEGORYID INT,EMPLOYEENAME NVARCHAR(10),CATEGORYNAME NVARCHAR(30))

SELECT * FROM OUTBOUND.SUMM




