--25-05-18

select * from ref.SALESDETAILS_N
select * from ref.[sales details]
select * from OUTBOUND.SUMM with(nolock)
select * from ref.DIM_EMPLOYEE
select * from ref.DIM_PRODUCT

SELECT OS.EMPLOYEEID,OS.EMPLOYEENAME,ROUND(SUM(UNITPRICE*QUANTITY),2) AS TOTALSALE,DATENAME(MONTH,SALEDATE) AS MONTHSALE,SN.SALESID
FROM REF.SALESDETAILS_N SN
JOIN OUTBOUND.SUMM OS ON OS.SALESID=SN.SALESID
WHERE SN.SALESID  BETWEEN 10248 AND 10250
GROUP BY os.EMPLOYEEID,os.EMPLOYEENAME,SN.SALESID,DATENAME(MONTH,SALEDATE)

--TOTAL SALES OF AN EMPLOYEE WITH MONTH
SELECT ROUND(SUM(UNITPRICE*QUANTITY), 2) AS TOTALSALES,SN.SALESID,DATENAME(MONTH,SALEDATE) AS MONTHSALE,OS.EMPLOYEEID,OS.EMPLOYEENAME FROM REF.SALESDETAILS_N SN
JOIN OUTBOUND.SUMM OS ON OS.SALESID=SN.SALESID
WHERE SN.SALESID BETWEEN 10248 AND 10249
GROUP BY SN.SALESID,DATENAME(MONTH,SALEDATE),OS.EMPLOYEEID,OS.EMPLOYEENAME


--MAX SALE
SELECT ROUND(MAX(UNITPRICE*QUANTITY), 2) AS MAXSALE,OS.EMPLOYEENAME,OS.EMPLOYEEID,SN.SALESID
FROM REF.SALESDETAILS_N SN
JOIN OUTBOUND.SUMM OS ON OS.SALESID=SN.SALESID
WHERE SN.SALESID BETWEEN 10248 AND 10283
GROUP BY OS.EMPLOYEEID,OS.EMPLOYEENAME,SN.SALESID

SELECT ROUND(SUM(UNITPRICE*QUANTITY),2),SALESID FROM REF.SALESDETAILS_N
GROUP BY SALESID

SELECT MAX(UNITPRICE*QUANTITY),OS.EMPLOYEEID,OS.EMPLOYEENAME
FROM REF.SALESDETAILS_N SN
JOIN OUTBOUND.SUMM OS ON OS.SALESID=SN.SALESID
WHERE SN.SALESID BETWEEN 10248 AND 10250
GROUP BY OS.EMPLOYEEID,OS.EMPLOYEENAME

SELECT OS.EMPLOYEEID,OS.EMPLOYEENAME
FROM OUTBOUND.SUMM OS
JOIN REF.SALESDETAILS_N SN ON SN.SALESID=OS.SALESID
WHERE SN.SALESID BETWEEN 10248 AND 10250
GROUP BY OS.EMPLOYEEID,OS.EMPLOYEENAME
ORDER BY MAX(SN.UNITPRICE*SN.QUANTITY)




SELECT MAX(SN.UNITPRICE*SN.QUANTITY)as maxsale,OS.EMPLOYEENAME,OS.EMPLOYEEID
 from ref.SALESDETAILS_N SN
 JOIN OUTBOUND.SUMM OS ON OS.SALESID=SN.SALESID
 WHERE SN.SALESID BETWEEN 10248 AND 10250 
 AND
  SN.UNITPRICE*SN.QUANTITY=1696.00
   GROUP BY OS.EMPLOYEEID,OS.EMPLOYEENAME

 --RANKING
 SELECT ROUND(SUM(UNITPRICE*QUANTITY), 2) AS TOTALSALES,DATENAME(MONTH,SALEDATE) AS MONTHSALE,OS.EMPLOYEEID,OS.EMPLOYEENAME,DENSE_RANK() OVER(PARTITION BY OS.EMPLOYEEID ORDER BY ROUND(SUM(UNITPRICE*QUANTITY), 2 )DESC)AS RANK
  FROM REF.SALESDETAILS_N SN
JOIN OUTBOUND.SUMM OS ON OS.SALESID=SN.SALESID
WHERE SN.SALESID BETWEEN 10248 AND 10528
GROUP BY DATENAME(MONTH,SALEDATE),OS.EMPLOYEEID,OS.EMPLOYEENAME












 