drop table dbo.anubhav
drop table dbo.[check]
drop table dbo.DimCustomer
alter table dbo.dimcustomer
drop pk_dimcustomer

alter table factsales
drop [FK_FactSales_DimCustomer]

drop table dbo.dimcustomer 
alter table factsales
drop [FK_FactSales_DimDate] 

drop table dbo.DimDate

alter table dbo.dimdate
drop PK_DimDate
alter table dbo.factsales
drop [FK_FactSales_DimDate1]

 alter table dbo.dimproduct
drop [FK_DimProduct_FactSales]

drop table dbo.DimProduct

UPDATE REF.[sales details]
SET SALEDATE=CAST('2016-05-23' AS DATETIME)
WHERE SALESID BETWEEN 10345 AND 10380

select * from ref.[sales details]

select * from ref.SALESDETAILS_N
alter table ref.salesdetails_n
add saledate datetime


--fill saledate column

select * from ref.SALESDETAILS_N

UPDATE REF.[salesdetails_n]
SET SALEDATE=CAST('2016-05-23' AS DATETIME)
WHERE SALESID BETWEEN 10248 AND 10282

UPDATE REF.[salesdetails_n]
SET SALEDATE=CAST('2016-06-23' AS DATETIME)
WHERE SALESID BETWEEN 10283 AND 10315

UPDATE REF.[salesdetails_n]
SET SALEDATE=CAST('2016-07-23' AS DATETIME)
WHERE SALESID BETWEEN 10316 AND 10350

UPDATE REF.[salesdetails_n]
SET SALEDATE=CAST('2016-08-23' AS DATETIME)
WHERE SALESID BETWEEN 10351 AND 10385

UPDATE REF.[salesdetails_n]
SET SALEDATE=CAST('2016-09-23' AS DATETIME)
WHERE SALESID BETWEEN 10386 AND 10418

UPDATE REF.[salesdetails_n]
SET SALEDATE=CAST('2016-10-23' AS DATETIME)
WHERE SALESID BETWEEN 10419 AND 10454

UPDATE REF.[salesdetails_n]
SET SALEDATE=CAST('2016-11-23' AS DATETIME)
WHERE SALESID BETWEEN 10455 AND 10489

UPDATE REF.[salesdetails_n]
SET SALEDATE=CAST('2016-12-23' AS DATETIME)
WHERE SALESID BETWEEN 10490 AND 10524

UPDATE REF.[salesdetails_n]
SET SALEDATE=CAST('2017-01-23' AS DATETIME)
WHERE SALESID BETWEEN 10525 AND 10554

UPDATE REF.[salesdetails_n]
SET SALEDATE=CAST('2017-02-23' AS DATETIME)
WHERE SALESID BETWEEN 10555 AND 10591

UPDATE REF.[salesdetails_n]
SET SALEDATE=CAST('2017-03-23' AS DATETIME)
WHERE SALESID BETWEEN 10592 AND 10626

UPDATE REF.[salesdetails_n]
SET SALEDATE=CAST('2017-04-23' AS DATETIME)
WHERE SALESID BETWEEN 10627 AND 10666

UPDATE REF.[salesdetails_n]
SET SALEDATE=CAST('2017-05-23' AS DATETIME)
WHERE SALESID BETWEEN 10666 AND 10698

INSERT INTO OUTBOUND.SUMM
SELECT 
	A.SALESID,A.EMPLOYEEID,A.ITEMID,
	C.CUSTOMERID,C.CONTACTNAME,C.ADDRESS,C.COMPANYNAME,
	D.PRODUCTNAME,D.SUPPLIERID,D.categoryid,
	E.EMPLOYEENAME,
	F.CATEGORYNAME

FROM MART.SALES A 
INNER JOIN REF.LKP_CUST_SALES B ON A.SALESID = B.salesid
INNER JOIN REF.DIM_CUSTOMER C ON B.customerid = C.CUSTOMERID
INNER JOIN REF.DIM_PRODUCT D ON A.itemid=D.itemid
INNER JOIN REF.DIM_EMPLOYEE E ON A.EMPLOYEEID=E.EMPLOYEEID
INNER JOIN REF.DIM_CATEGORY F ON D.categoryid=F.CATEGORYID
where A.SALESID between 10651 and 10671


select * from OUTBOUND.SUMM
