--CREATING THE REFRENCE SCHEMA(16-05-18)

CREATE SCHEMA REF
GO
CREATE TABLE REF.DIM_CUSTOMER(CUSTOMERID NCHAR(5) CONSTRAINT pk_cid PRIMARY KEY NOT NULL,COMPANYNAME NVARCHAR(40) NOT NULL,CONTACTNAME NVARCHAR(30),CONTACTTITLE NVARCHAR(30),ADDRESS NVARCHAR(60),CITY NVARCHAR(15),REGION NVARCHAR(15),POSTALCODE NVARCHAR(10),COUNTRY NVARCHAR(15),PHONE  NVARCHAR(24),FAX NVARCHAR(24),CUSTOMERKEY INT  NOT NULL)
insert into ref.DIM_CUSTOMER select * from DimCustomer1

select * from ref.DIM_CUSTOMER


CREATE TABLE ref.category(categoryid int ,categoryname nvarchar(30) null)
insert into ref.category(categoryid,categoryname)
select categoryid,CategoryName from [Sales by Category]
alter table ref.category
drop constraint pk_cd 

select DISTINCT * from ref.category



--REFERENCE EMPLOYEE

SET IDENTITY_INSERT REF.DIMEMPLOYEE ON;

CREATE TABLE ref.DIM_EMPLOYEE(EMPLOYEEID INT CONSTRAINT PK_EID PRIMARY KEY NOT NULL,EMPLOYEENAME NVARCHAR(10),EMPLOYEETITLE NVARCHAR(20),TITLE NVARCHAR(30),BIRTHDATE DATETIME,HIREDATE DATETIME,ADDRESS NVARCHAR(60),CITY NVARCHAR(15),REGION NVARCHAR(15),COUNTRY NVARCHAR(15))

INSERT INTO REF.DIM_EMPLOYEE(EMPLOYEENAME,EMPLOYEETITLE,TITLE,BIRTHDATE,HIREDATE,ADDRESS,CITY,REGION,COUNTRY)
SELECT EMPLOYEENAME,EMPLOYEETITLE,TITLE,BIRTHDATE,HIREDATE,ADDRESS,CITY,REGION,COUNTRY FROM DimEmployee1

ALTER TABLE REF.DIM_EMPLOYEE
ADD  EMPLOYEEID INT NOT NULL IDENTITY
SELECT * FROM REF.DIM_EMPLOYEE

ALTER TABLE REF.DIM_EMPLOYEE
ADD CONSTRAINT PK_E_ID PRIMARY KEY(EMPLOYEEID)


--CREATING THE REFERENCE DIM_SUPPLIER


CREATE TABLE REF.DIM_SUPPLIER(SUPPLIERID INT CONSTRAINT PK_SUPP_ID PRIMARY KEY,COMPANYNAME NVARCHAR(40),CONTACTNAME NVARCHAR(30),ADDRESS NVARCHAR(60),CITY NVARCHAR(15),REGION NVARCHAR(15),COUNTRY NVARCHAR(15),PHONE NVARCHAR(24))
INSERT INTO REF.DIM_SUPPLIER(SUPPLIERID,COMPANYNAME,CONTACTNAME,ADDRESS,CITY,REGION,COUNTRY,PHONE)
SELECT SUPPLIERID,COMPANYNAME,CONTACTNAME,ADDRESS,CITY,REGION,COUNTRY,PHONE FROM Suppliers

SELECT * FROM REF.DIM_SUPPLIER

CREATE TABLE REF.LKP_CUSTOMER_SALES(CATEGORYID INT,CUSTOMERID NCHAR(5) CONSTRAINT FK_C_ID FOREIGN KEY(CUSTOMERID) REFERENCES REF.DIM_CUSTOMER(CUSTOMERID),EMPLOYEEID INT CONSTRAINT FK_EMP_ID FOREIGN KEY(EMPLOYEEID) REFERENCES REF.DIM_EMPLOYEE(EMPLOYEEID),SUPPLIERID INT CONSTRAINT FK_SUPP_ID FOREIGN KEY(SUPPLIERID) REFERENCES REF.DIM_SUPPLIER(SUPPLIERID))

SELECT * FROM REF.LKP_CUSTOMER_SALES
ALTER TABLE REF.LKP_CUSTOMER_SALES
ADD CONSTRAINT FK_P_ID FOREIGN KEY(PRODUCTID) REFERENCES MART.SALES(SALESID) --setting up foreign key constraint

--inserting values to the lookup table


